# Multi Layer Perceptron (MLP) Back Propagation

Import Library

In [1]:
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

Menginisialisasikan dataset, weight dan kelas yang akan diprediksi dalam model

In [2]:
dataset =[[1, 0, 0, 0, 1, 0],
          [0, 1, 1, 1, 1, 0],
          [0, 0, 1, 0, 0, 1],
          [0, 0, 1, 0, 1, 0],
          [0, 1, 0, 0, 0, 1],
          [1, 0, 1, 0, 1, 1],
          [0, 0, 1, 1, 0, 0],
          [0, 1, 0, 1, 0, 0],
          [1, 0, 0, 1, 0, 1],
          [0, 1, 1, 1, 1, 1],
          [0, 0, 0, 1, 1, 0.9],
          [0, 0, 0, 1, 0.8, 1],
          [0, 0, 0, 1, 1, 0.75],
          [0, 0, 0, 1, 1, 1]]
    
weights = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
class_target = ['A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C']

Membuat matrix transpose dan Menerjemahkan class target ke dalam bentuk integer, dimana:
A = 1,
B = -1,
C = 0

In [3]:
#Transpose Matrix
class_target = np.array(class_target)
dataTr = np.arange(len(class_target))
dataTr[:] = 0

# Menerjemahkan class ke dalam bentuk integer
iD_dataTr = np.where(class_target == 'A')
dataTr[iD_dataTr] = 1
iD_dataTr = np.where(class_target == 'B')
dataTr[iD_dataTr] = -1
dataTr = dataTr.tolist()

Kode ini digunakan untuk melakukan transpose pada dataset, kemudian menambahkan dataTr sebagai baris terakhir dari dataset yang sudah ditranspose

In [4]:
transpseX = list(map(list, zip(*dataset)))
transpseX.append(dataTr)
dataInpTr = list(map(list, zip(*transpseX)))

In [5]:
dataInpTr

[[1, 0, 0, 0, 1, 0, 1],
 [0, 1, 1, 1, 1, 0, -1],
 [0, 0, 1, 0, 0, 1, 1],
 [0, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 0, 0, 1, 1],
 [1, 0, 1, 0, 1, 1, 1],
 [0, 0, 1, 1, 0, 0, -1],
 [0, 1, 0, 1, 0, 0, -1],
 [1, 0, 0, 1, 0, 1, -1],
 [0, 1, 1, 1, 1, 1, -1],
 [0, 0, 0, 1, 1, 0.9, 0],
 [0, 0, 0, 1, 0.8, 1, 0],
 [0, 0, 0, 1, 1, 0.75, 0],
 [0, 0, 0, 1, 1, 1, 0]]

In [6]:
# Convert menjadi numpy array
dataInpTr=np.array(dataInpTr)

Membuat model ANN menggunakan method MLPClassifier dari scikit-learn.

Dalam Pendefinisiannya, fungsi aktivasi yang digunakan adalah sigmoid. Method MLPClassifier menggunakan fungsi activation='logistic' untuk menerapkan sigmoid function dalam neural network.

In [7]:
print("Data Input = " )
print(dataInpTr)

# Persiapan data
x = dataInpTr[:,:-1]
y = dataInpTr[:,-1]

# Mendefinisikan ANN Backpropagation
mlp = MLPClassifier(learning_rate_init=0.25, activation='logistic', hidden_layer_sizes=(6,3), max_iter=100, alpha=1e-4, 
                    solver='sgd', verbose=0, tol=1e-4, random_state=1, batch_size=20)

Data Input = 
[[ 1.    0.    0.    0.    1.    0.    1.  ]
 [ 0.    1.    1.    1.    1.    0.   -1.  ]
 [ 0.    0.    1.    0.    0.    1.    1.  ]
 [ 0.    0.    1.    0.    1.    0.    1.  ]
 [ 0.    1.    0.    0.    0.    1.    1.  ]
 [ 1.    0.    1.    0.    1.    1.    1.  ]
 [ 0.    0.    1.    1.    0.    0.   -1.  ]
 [ 0.    1.    0.    1.    0.    0.   -1.  ]
 [ 1.    0.    0.    1.    0.    1.   -1.  ]
 [ 0.    1.    1.    1.    1.    1.   -1.  ]
 [ 0.    0.    0.    1.    1.    0.9   0.  ]
 [ 0.    0.    0.    1.    0.8   1.    0.  ]
 [ 0.    0.    0.    1.    1.    0.75  0.  ]
 [ 0.    0.    0.    1.    1.    1.    0.  ]]


In [8]:
print("============================ TRAINING ===========================" )
#Melakukan training
mlp.fit(x,y)
print("==> WEIGHT" )
print("Bobot antara input dan lapisan tersembunyi pertama : ")
print(mlp.coefs_[0])
print("\nBobot antara lapisan tersembunyi pertama dan lapisan tersembunyi kedua : ")
print(mlp.coefs_[1])
print("\nBobot antara lapisan tersembunyi kedua dan lapisan output : ")
print(mlp.coefs_[2])
print("\n============================ TRAINING RESULT ============================" )
i = 0;
for row in x:
    prediction = mlp.predict(row.reshape(1,-1))
    print("Expected=%d, Predicted=%d" % (y[i], prediction))
    i = i+1

============================ TRAINING ===========================
==> WEIGHT
Bobot antara input dan lapisan tersembunyi pertama : 
[[ 0.68401058  1.31243724 -1.34192955 -0.3379497  -0.81021362 -1.06203427]
 [ 0.12177952  0.98536997 -1.63958903  0.13281764 -0.40997788 -0.59450106]
 [ 0.39799419  1.23750036 -1.66032178  0.13236017 -0.60863335 -0.78738264]
 [-2.63963503 -2.66742894  1.24817169  1.36440729  1.14182542  1.43785099]
 [-0.26504229 -0.93698655  1.06640947 -0.28220198  0.21423581  0.9228577 ]
 [-0.03928549  0.04771054  0.75783867 -0.14549069  0.2366947  -0.0870834 ]]

Bobot antara lapisan tersembunyi pertama dan lapisan tersembunyi kedua : 
[[ 0.47260867  2.20130542 -2.22785787]
 [ 1.87034175  3.35298769 -2.47186611]
 [-2.38333901 -2.34585671  1.01442479]
 [ 0.82969421 -0.70370256  1.07479012]
 [-0.30496992 -0.96595747  0.93148426]
 [-0.99107438 -1.21106658  1.71560145]]

Bobot antara lapisan tersembunyi kedua dan lapisan output : 
[[ 1.39742626 -2.9368748   0.96307868]
 [ 0.14

/home/mizanul/Documents/code/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:609: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn(
/home/mizanul/Documents/code/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/tmp/ipykernel_48838/1224418573.py:15: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("Expected=%d, Predicted=%d" % (y[i], prediction))
/tmp/ipykernel_48838/1224418573.py:15: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your arr

In [9]:
dataset_testing = train_test_split(dataset, dataTr, test_size = 0.2, stratify = dataTr)
trainX, testX, trainY, testY = dataset_testing

Membuat model ANN Back Propagation menggunakan method MLPClassifier dari scikit-learn.

Dalam Pendefinisiannya, fungsi aktivasi yang digunakan adalah sigmoid. Method MLPClassifier menggunakan fungsi activation='logistic' untuk menerapkan sigmoid function dalam neural network.

In [10]:
#Pembuatan ANN Back Propagation
mlpBP = MLPClassifier(learning_rate_init=0.5, activation='logistic', hidden_layer_sizes=(10,5), max_iter=5000, 
                      alpha=1e-4, solver='lbfgs', verbose=0, tol=1e-4, random_state=1)

#Melakukan TRAINNING
mlpBP.fit(trainX, trainY)

MLPClassifier(activation='logistic', hidden_layer_sizes=(10, 5),
              learning_rate_init=0.5, max_iter=5000, random_state=1,
              solver='lbfgs', verbose=0)

Inisialisasi fungsi evaluasi model

In [11]:
def generateClassificationReport(y_test,y_pred):
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print('Accuracy ', accuracy_score(y_test,y_pred))

In [12]:
print("\n===================== HASIL PREDIKSI TRAINING ======================" )
pred_y = mlpBP.predict(trainX)
generateClassificationReport(trainY,pred_y)


===================== HASIL PREDIKSI TRAINING ======================
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         4
           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         4

    accuracy                           1.00        11
   macro avg       1.00      1.00      1.00        11
weighted avg       1.00      1.00      1.00        11

[[4 0 0]
 [0 3 0]
 [0 0 4]]
Accuracy  1.0


In [13]:
print("\n===================== HASIL PREDIKSI TESTING ======================" )
pred_y = mlpBP.predict(testX)
generateClassificationReport(testY, pred_y)


===================== HASIL PREDIKSI TESTING ======================
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         1
           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Accuracy  1.0
