# Perceptron (Single Layer)

Import Library

In [1]:
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

Menginisialisasikan dataset, weight dan kelas yang akan diprediksi dalam model

In [2]:
dataset =[[1, 0, 0, 0, 1, 0],
          [0, 1, 1, 1, 1, 0],
          [0, 0, 1, 0, 0, 1],
          [0, 0, 1, 0, 1, 0],
          [0, 1, 0, 0, 0, 1],
          [1, 0, 1, 0, 1, 1],
          [0, 0, 1, 1, 0, 0],
          [0, 1, 0, 1, 0, 0],
          [1, 0, 0, 1, 0, 1],
          [0, 1, 1, 1, 1, 1],
          [0, 0, 0, 1, 1, 0.9],
          [0, 0, 0, 1, 0.8, 1],
          [0, 0, 0, 1, 1, 0.75],
          [0, 0, 0, 1, 1, 1]]
    
weights = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
class_target = ['A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C']

Menerjemahkan class target ke dalam bentuk integer, dimana:
A = 1,
B = -1,
C = 0

In [3]:
# Membuat matrix baru
class_target = np.array(class_target)
dataTr = np.arange(len(class_target))
dataTr[:] = 0

# Menerjemahkan class ke dalam bentuk integer
iD_dataTr = np.where(class_target == 'A')
dataTr[iD_dataTr] = 1
iD_dataTr = np.where(class_target == 'B')
dataTr[iD_dataTr] = -1
dataTr = dataTr.tolist()

In [4]:
dataTr

[1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 0, 0, 0, 0]

Kode di bawah ini digunakan untuk melakukan transpose pada dataset, kemudian menambahkan dataTr sebagai baris terakhir dari dataset yang sudah ditranspose

In [5]:
transpseX = list(map(list, zip(*dataset)))
transpseX.append(dataTr)
dataInpTr = list(map(list, zip(*transpseX)))

In [6]:
dataInpTr

[[1, 0, 0, 0, 1, 0, 1],
 [0, 1, 1, 1, 1, 0, -1],
 [0, 0, 1, 0, 0, 1, 1],
 [0, 0, 1, 0, 1, 0, 1],
 [0, 1, 0, 0, 0, 1, 1],
 [1, 0, 1, 0, 1, 1, 1],
 [0, 0, 1, 1, 0, 0, -1],
 [0, 1, 0, 1, 0, 0, -1],
 [1, 0, 0, 1, 0, 1, -1],
 [0, 1, 1, 1, 1, 1, -1],
 [0, 0, 0, 1, 1, 0.9, 0],
 [0, 0, 0, 1, 0.8, 1, 0],
 [0, 0, 0, 1, 1, 0.75, 0],
 [0, 0, 0, 1, 1, 1, 0]]

Menggunakan fungsi aktivasi Bipolar dalam code dan membuat fungsi prediksi untuk mengupdate nilai y pada setiap iterasi


In [7]:
# Fungsi aktivasi dengan fungsi bipolar
def bipolar_step_function(threshold=0, x=0):
    return 1.0 if x >= threshold else -1.0

# Membuat prediksi dengan weights
def prediction(row, weights, threshold=0.0):
    # Bias
    y_in = weights[0]
    for i in range(len(row) - 1):
        y_in += weights[i + 1] * row[i]
    y = bipolar_step_function(threshold, y_in)
    return y

In [8]:
# Mencoba Activation Function
bipolar_test = bipolar_step_function(0,5)
print(bipolar_test)

1.0


In [9]:
# Mencoba fungsi prediksi
t = dataset[5]
print(t)
print(weights)
prediction1 = prediction(t, weights)
print("Expected=%d, Predicted=%d" % (t[-1], prediction1))

[1, 0, 1, 0, 1, 1]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Expected=1, Predicted=1


Membuat skema Training menggunakan metode Perceptron dan menghitung nilai error pada setiap iterasi

In [10]:
def train_weights(train, l_rate, n_epoch, threshold=0.0):
    weights = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        sum_error = 0.0
        for row in train:
            prediction1 = prediction(row, weights, threshold)
            error = row[-1] - prediction1
            sum_error += error**2
            weights[0] = weights[0] + l_rate * error
            for i in range(len(row) - 1):
                weights[i + 1] = weights[i + 1] + l_rate * error * row[i]
        print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
    return weights

Membuat fungsi testing untuk melakukan testing pada model dengan menggunakan data yang bisa dikustomisasi

In [11]:
def testing(data):
    true_labels = []
    predicted_labels = []
    for row in data:
        prediction1 = prediction(row, weights, threshold)
        # Konversi hasil prediksi ke label kelas
        if prediction1 == 1.0:
            predicted_label = 'A'
        elif prediction1 == -1.0:
            predicted_label = 'B'
        else:
            predicted_label = 'C'
        expected_label = row[-1]
        print("Expected={}, \tPredicted={} ({})".format(expected_label, prediction1, predicted_label))
        
        true_labels.append(expected_label*1.0)
        predicted_labels.append(prediction1)
    return true_labels, predicted_labels

### Drive Code

Cell ini berfungsi sebagai main/drive code untuk meanggunakan model single layer yang sudah dibuat sebelumnya.

Terdapat beberapa parameter yang perlu diisi antara lain l_rate, n_epoch, dan treshold.

In [12]:
l_rate = 0.05
n_epoch = 50
threshold = 0.2  # Threshold digunakan pada fungsi aktivasi bipolar
weights = train_weights(dataInpTr, l_rate, n_epoch, threshold)
print('Weights : ', weights)

>epoch=0, lrate=0.050, error=24.000
>epoch=1, lrate=0.050, error=12.000
>epoch=2, lrate=0.050, error=8.000
>epoch=3, lrate=0.050, error=12.000
>epoch=4, lrate=0.050, error=4.000
>epoch=5, lrate=0.050, error=8.000
>epoch=6, lrate=0.050, error=4.000
>epoch=7, lrate=0.050, error=4.000
>epoch=8, lrate=0.050, error=4.000
>epoch=9, lrate=0.050, error=4.000
>epoch=10, lrate=0.050, error=4.000
>epoch=11, lrate=0.050, error=4.000
>epoch=12, lrate=0.050, error=4.000
>epoch=13, lrate=0.050, error=12.000
>epoch=14, lrate=0.050, error=4.000
>epoch=15, lrate=0.050, error=4.000
>epoch=16, lrate=0.050, error=4.000
>epoch=17, lrate=0.050, error=4.000
>epoch=18, lrate=0.050, error=8.000
>epoch=19, lrate=0.050, error=8.000
>epoch=20, lrate=0.050, error=4.000
>epoch=21, lrate=0.050, error=4.000
>epoch=22, lrate=0.050, error=4.000
>epoch=23, lrate=0.050, error=4.000
>epoch=24, lrate=0.050, error=4.000
>epoch=25, lrate=0.050, error=4.000
>epoch=26, lrate=0.050, error=4.000
>epoch=27, lrate=0.050, error=4.00

### Testing

Menginisialisasi data testing. Dalam hal ini data testing yang digunakan sama dengan data latih untuk mengukur akurasi model perceptron yang sudah dibangun

In [13]:
data_testing = [[1, 0, 0, 0, 1, 0, 1],
                [0, 1, 1, 1, 1, 0, -1],
                [0, 0, 1, 0, 0, 1, 1],
                [0, 0, 1, 0, 1, 0, 1],
                [0, 1, 0, 0, 0, 1, 1],
                [1, 0, 1, 0, 1, 1, 1],
                [0, 0, 1, 1, 0, 0, -1],
                [0, 1, 0, 1, 0, 0, -1],
                [1, 0, 0, 1, 0, 1, -1],
                [0, 1, 1, 1, 1, 1, -1],
                [0, 0, 0, 1, 1, 0.9, 0],
                [0, 0, 0, 1, 0.8, 1, 0],
                [0, 0, 0, 1, 1, 0.75, 0],
                [0, 0, 0, 1, 1, 1, 0]]

Membuat Metrik evaluasi <b>berupa accuracy</b>, <b>confusion matrix</b> dan <b>classification</b> report menggunakan library scikit-learn

In [14]:
true_labels, predicted_labels = testing(data_testing)

accuracy = accuracy_score(true_labels, predicted_labels)
print("\n\nAkurasi: %.2f%%" % accuracy)

# Menghitung dan mencetak confusion matrix
confusion = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
print(confusion)

# Mencetak classification report
classification_rep = classification_report(true_labels, predicted_labels, target_names=['A', 'B', 'C'])
print("\nClassification Report:")
print(classification_rep)

Expected=1, 	Predicted=1.0 (A)
Expected=-1, 	Predicted=-1.0 (B)
Expected=1, 	Predicted=1.0 (A)
Expected=1, 	Predicted=1.0 (A)
Expected=1, 	Predicted=1.0 (A)
Expected=1, 	Predicted=1.0 (A)
Expected=-1, 	Predicted=-1.0 (B)
Expected=-1, 	Predicted=-1.0 (B)
Expected=-1, 	Predicted=-1.0 (B)
Expected=-1, 	Predicted=-1.0 (B)
Expected=0, 	Predicted=-1.0 (B)
Expected=0, 	Predicted=-1.0 (B)
Expected=0, 	Predicted=-1.0 (B)
Expected=0, 	Predicted=-1.0 (B)


Akurasi: 0.71%
Confusion Matrix:
[[5 0 0]
 [4 0 0]
 [0 0 5]]

Classification Report:
              precision    recall  f1-score   support

           A       0.56      1.00      0.71         5
           B       0.00      0.00      0.00         4
           C       1.00      1.00      1.00         5

    accuracy                           0.71        14
   macro avg       0.52      0.67      0.57        14
weighted avg       0.56      0.71      0.61        14



/home/mizanul/Documents/code/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mizanul/Documents/code/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mizanul/Documents/code/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r